/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Content Info
         * @description Get metadata for a YouTube Music URL.
         *
         *     Returns title, artist, kind, track count, year, and thumbnail
         *     from a single API call without running the full extraction pipeline.
         */
        get: operations["get_content_info_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List all jobs (oldest first, FIFO order).
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a new sync job.
         *
         *     Jobs are queued and executed sequentially. Returns 409 if queue is full.
         */
        post: operations["create_job_jobs_post"];
        /**
         * Clear Jobs
         * @description Clear all completed/failed/cancelled jobs.
         *
         *     Running and queued jobs are not affected.
         */
        delete: operations["clear_jobs_jobs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a running or queued job.
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a completed, failed, or cancelled job.
         *
         *     Running or queued jobs cannot be deleted.
         */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job events via SSE
         * @description On connect, sends a snapshot event with all current jobs, then streams events as they occur. Heartbeat comments sent every 30s.
         */
        get: operations["stream_jobs_jobs_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get buffered log entries
         * @description Returns all currently buffered log entries as an array.
         */
        get: operations["get_logs_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream log entries via SSE
         * @description On connect, sends all buffered log entries, then streams new entries as they arrive. Heartbeat comments sent every 30s.
         */
        get: operations["stream_logs_logs_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cookies/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cookies Status
         * @description Check if cookies file is configured.
         */
        get: operations["cookies_status_cookies_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cookies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Cookies
         * @description Upload cookies.txt content (Netscape format).
         *
         *     The cookie file enables downloading from private playlists
         *     and accessing age-restricted content on YouTube Music.
         */
        post: operations["upload_cookies_cookies_post"];
        /**
         * Delete Cookies
         * @description Delete the cookies file.
         */
        delete: operations["delete_cookies_cookies_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync All Subscriptions
         * @description Sync all enabled subscriptions.
         */
        post: operations["sync_all_subscriptions_subscriptions_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subscriptions
         * @description List all subscriptions.
         */
        get: operations["list_subscriptions_subscriptions_get"];
        put?: never;
        /**
         * Create Subscription
         * @description Create a new subscription.
         */
        post: operations["create_subscription_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Subscription
         * @description Delete a subscription.
         */
        delete: operations["delete_subscription_subscriptions__subscription_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Subscription
         * @description Update a subscription.
         */
        patch: operations["update_subscription_subscriptions__subscription_id__patch"];
        trace?: never;
    };
    "/subscriptions/{subscription_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Subscription
         * @description Sync a single subscription.
         */
        post: operations["sync_subscription_subscriptions__subscription_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scheduler Status
         * @description Get scheduler status (read-only).
         */
        get: operations["get_scheduler_status_scheduler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Discovery Settings
         * @description Get Last.fm discovery settings.
         */
        get: operations["get_discovery_settings_discovery_settings_get"];
        /**
         * Update Discovery Settings
         * @description Update Last.fm discovery settings.
         */
        put: operations["update_discovery_settings_discovery_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Lastfm
         * @description Connect a Last.fm account.
         */
        post: operations["connect_lastfm_discovery_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect Lastfm
         * @description Disconnect Last.fm and clear suggestions.
         */
        post: operations["disconnect_lastfm_discovery_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Discovery Scan
         * @description Run a discovery scan.
         */
        post: operations["run_discovery_scan_discovery_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Suggestions
         * @description List discovery suggestions.
         */
        get: operations["list_suggestions_discovery_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Discovery Stats
         * @description Get discovery statistics.
         */
        get: operations["get_discovery_stats_discovery_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/suggestions/{suggestion_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Suggestion
         * @description Approve a suggestion and enqueue download.
         */
        post: operations["approve_suggestion_discovery_suggestions__suggestion_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/suggestions/{suggestion_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Suggestion
         * @description Reject a suggestion.
         */
        post: operations["reject_suggestion_discovery_suggestions__suggestion_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/suggestions/bulk-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Approve Suggestions
         * @description Bulk approve suggestions.
         */
        post: operations["bulk_approve_suggestions_discovery_suggestions_bulk_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/playlists/similar-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Similar Tracks Playlist
         * @description Generate a similar-tracks playlist (Discover Weekly-style).
         */
        post: operations["generate_similar_tracks_playlist_api_discovery_playlists_similar_tracks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery/playlists/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Discover Playlist
         * @description Approve all pending and create a Discover playlist M3U.
         */
        post: operations["create_discover_playlist_discovery_playlists_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioCodec
         * @description Supported audio output codecs.
         * @enum {string}
         */
        AudioCodec: "opus" | "mp3" | "m4a";
        /**
         * BulkApproveRequest
         * @description Request to bulk-approve suggestions.
         */
        BulkApproveRequest: {
            /** Suggestion Ids */
            suggestion_ids?: string[] | null;
        };
        /**
         * CancelJobResponse
         * @description Response when a job is cancelled.
         */
        CancelJobResponse: {
            /**
             * Message
             * @default Job cancelled
             * @constant
             */
            message: "Job cancelled";
        };
        /**
         * ClearJobsResponse
         * @description Response when jobs are cleared.
         */
        ClearJobsResponse: {
            /** Cleared */
            cleared: number;
        };
        /**
         * ContentInfo
         * @description Information about downloaded content (album, playlist, or track).
         */
        ContentInfo: {
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /**
             * Year
             * @default null
             */
            year: number | null;
            /**
             * Track Count
             * @default null
             */
            track_count: number | null;
            /**
             * Playlist Id
             * @default
             */
            playlist_id: string;
            /**
             * Url
             * Format: uri
             * @default null
             */
            url: string | null;
            /**
             * Thumbnail Url
             * Format: uri
             * @default null
             */
            thumbnail_url: string | null;
            /**
             * Audio Codec
             * @default null
             */
            audio_codec: string | null;
            /**
             * Audio Bitrate
             * @default null
             */
            audio_bitrate: number | null;
            /** @default playlist */
            kind: components["schemas"]["ContentKind"];
        };
        /**
         * ContentKind
         * @description Type of music content (album vs playlist vs track).
         * @enum {string}
         */
        ContentKind: "album" | "playlist" | "track";
        /**
         * CookiesStatusResponse
         * @description Cookies status response model.
         */
        CookiesStatusResponse: {
            /** Configured */
            configured: boolean;
        };
        /**
         * CookiesUploadRequest
         * @description Cookies upload request model.
         */
        CookiesUploadRequest: {
            /** Content */
            content: string;
        };
        /**
         * CookiesUploadResponse
         * @description Cookies upload response model.
         */
        CookiesUploadResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * CreateJobRequest
         * @description Request to create a new sync job.
         */
        CreateJobRequest: {
            /**
             * Url
             * Format: uri
             * @description YouTube or YouTube Music playlist, album, or single track URL
             * @example https://music.youtube.com/playlist?list=OLAK5uy_...
             * @example https://www.youtube.com/watch?v=VIDEO_ID
             */
            url: string;
            /**
             * Max Items
             * @description Maximum number of tracks to download
             */
            max_items?: number | null;
        };
        /**
         * DiscoverPlaylistResponse
         * @description Response from creating a Discover playlist.
         */
        DiscoverPlaylistResponse: {
            /** Approved */
            approved: number;
            /** Playlist Tracks */
            playlist_tracks: number;
            /** Playlist Path */
            playlist_path?: string | null;
        };
        /**
         * DiscoveryScanResponse
         * @description Response from a discovery scan.
         */
        DiscoveryScanResponse: {
            /** New Suggestions */
            new_suggestions: number;
            /** Total Pending */
            total_pending: number;
        };
        /**
         * DiscoveryStatsResponse
         * @description Discovery statistics.
         */
        DiscoveryStatsResponse: {
            /** Pending */
            pending: number;
            /** Approved */
            approved: number;
            /** Rejected */
            rejected: number;
            /** Downloaded */
            downloaded: number;
        };
        /**
         * DiscoverySuggestionListResponse
         * @description List of discovery suggestions.
         */
        DiscoverySuggestionListResponse: {
            /** Items */
            items: components["schemas"]["DiscoverySuggestionResponse"][];
        };
        /**
         * DiscoverySuggestionResponse
         * @description Discovery suggestion response.
         */
        DiscoverySuggestionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lastfm Artist */
            lastfm_artist: string;
            /** Lastfm Track */
            lastfm_track: string;
            /** Matched Video Id */
            matched_video_id: string | null;
            /** Matched Title */
            matched_title: string | null;
            /** Matched Artist */
            matched_artist: string | null;
            /** Confidence */
            confidence: number;
            /** Artist Similarity */
            artist_similarity: number;
            /** Title Similarity */
            title_similarity: number;
            status: components["schemas"]["SuggestionStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job Id */
            job_id: string | null;
        };
        /**
         * ErrorResponse
         * @description Standard error response format.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response model.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "healthy";
        };
        /**
         * Job
         * @description A background sync job.
         */
        Job: {
            /** Id */
            id: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** @default opus */
            audio_format: components["schemas"]["AudioCodec"];
            /**
             * Max Items
             * @default null
             */
            max_items: number | null;
            /**
             * Subscription Id
             * @default null
             */
            subscription_id: string | null;
            /** @default manual */
            source: components["schemas"]["JobSource"];
            /** @default pending */
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** @default null */
            content_info: components["schemas"]["ContentInfo"] | null;
            /** @default null */
            download_stats: components["schemas"]["PhaseStats"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
        };
        /**
         * JobCreatedResponse
         * @description Response when a job is created.
         */
        JobCreatedResponse: {
            /** Id */
            id: string;
            /**
             * Message
             * @default Job created
             * @constant
             */
            message: "Job created";
        };
        /**
         * JobSource
         * @description Source of a background job.
         * @enum {string}
         */
        JobSource: "manual" | "scheduler";
        /**
         * JobStatus
         * @description Status of a background job.
         * @enum {string}
         */
        JobStatus: "pending" | "fetching_info" | "downloading" | "importing" | "completed" | "failed" | "cancelled";
        /**
         * JobsResponse
         * @description Response for listing jobs.
         */
        JobsResponse: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /**
         * LastFmConnectRequest
         * @description Request to connect a Last.fm account.
         */
        LastFmConnectRequest: {
            /** Username */
            username: string;
            /** Api Key */
            api_key: string;
        };
        /**
         * LastFmSettingsResponse
         * @description Last.fm settings response.
         */
        LastFmSettingsResponse: {
            /** Username */
            username: string;
            /** Enabled */
            enabled: boolean;
            /** Auto Download */
            auto_download: boolean;
            /** Confidence Threshold */
            confidence_threshold: number;
            /** Schedule Cron */
            schedule_cron: string;
        };
        /**
         * LastFmSettingsUpdate
         * @description Request to update Last.fm settings.
         */
        LastFmSettingsUpdate: {
            /** Username */
            username?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Auto Download */
            auto_download?: boolean | null;
            /** Confidence Threshold */
            confidence_threshold?: number | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
        };
        /**
         * LogEntry
         * @description Structured log entry sent to frontend via SSE.
         *
         *     Each log line from the backend is serialized as JSON using this schema.
         *     The frontend parses these entries and applies theme-aware styling.
         *
         *     The `entry_type` field enables discriminated union pattern matching
         *     in TypeScript for exhaustive type narrowing.
         * @example {
         *       "entry_type": "phase",
         *       "level": "INFO",
         *       "message": "Extracting metadata from playlist",
         *       "phase": "extracting",
         *       "phase_num": 1,
         *       "timestamp": "11:09:53"
         *     }
         * @example {
         *       "current": 1,
         *       "entry_type": "progress",
         *       "event_type": "track_download",
         *       "level": "INFO",
         *       "message": "Queen - Bohemian Rhapsody",
         *       "timestamp": "11:09:54",
         *       "total": 10,
         *       "track_artist": "Queen",
         *       "track_title": "Bohemian Rhapsody"
         *     }
         * @example {
         *       "entry_type": "stats",
         *       "level": "INFO",
         *       "message": "Downloads complete",
         *       "stats": {
         *         "failed": 0,
         *         "skipped_by_reason": {
         *           "file_exists": 2
         *         },
         *         "stats_type": "download",
         *         "success": 8
         *       },
         *       "timestamp": "11:09:55"
         *     }
         */
        LogEntry: {
            /**
             * Entry Type
             * @description Entry type for discriminated union matching
             * @default default
             * @enum {string}
             */
            entry_type: "header" | "phase" | "stats" | "progress" | "status" | "file" | "default";
            /**
             * Timestamp
             * @description Log timestamp in HH:MM:SS format
             */
            timestamp: string;
            /**
             * Level
             * @description Log level: DEBUG, INFO, WARNING, ERROR
             */
            level: string;
            /**
             * Message
             * @description Human-readable log message
             */
            message: string;
            /**
             * Phase
             * @description Current operation phase
             * @default null
             */
            phase: ("extracting" | "downloading" | "composing" | "normalizing") | null;
            /**
             * Phase Num
             * @description Phase number (1-4)
             * @default null
             */
            phase_num: number | null;
            /**
             * Event Type
             * @description Specific event type for granular tracking
             * @default null
             */
            event_type: "track_download" | null;
            /**
             * Current
             * @description Current item index in progress (0-indexed)
             * @default null
             */
            current: number | null;
            /**
             * Total
             * @description Total number of items to process
             * @default null
             */
            total: number | null;
            /**
             * Status
             * @description Operation result status
             * @default null
             */
            status: ("success" | "skipped" | "failed") | null;
            /**
             * @description Aggregate statistics for batch operations
             * @default null
             */
            stats: components["schemas"]["LogStats"] | null;
            /**
             * File Path
             * @description Path to generated or downloaded file
             * @default null
             */
            file_path: string | null;
            /**
             * File Type
             * @description Type of file: m3u, cover, audio
             * @default null
             */
            file_type: ("m3u" | "cover" | "audio") | null;
            /**
             * Track Title
             * @description Track title being processed
             * @default null
             */
            track_title: string | null;
            /**
             * Track Artist
             * @description Track artist name
             * @default null
             */
            track_artist: string | null;
            /**
             * Header
             * @description Section header text for visual separation
             * @default null
             */
            header: string | null;
        };
        /**
         * LogStats
         * @description Statistics for batch operations.
         *
         *     Uses a discriminator field (stats_type) for frontend type narrowing,
         *     and dictionary-based skip reason counts for scalability.
         *
         *     Attributes:
         *         stats_type: Discriminator indicating extraction or download stats.
         *         success: Number of successful operations.
         *         failed: Number of failed operations.
         *         skipped_by_reason: Count of skipped items by reason.
         */
        LogStats: {
            /**
             * Stats Type
             * @description Type of stats: 'extraction' or 'download'
             * @enum {string}
             */
            stats_type: "extraction" | "download";
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Cached
             * @default 0
             */
            cached: number;
            /**
             * Unmatched
             * @default 0
             */
            unmatched: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Skipped By Reason
             * @description Count of skipped items by reason
             */
            skipped_by_reason?: {
                [key: string]: number;
            };
        };
        /**
         * PhaseStats
         * @description Statistics for a processing phase (extraction or download).
         *
         *     Uses dictionary-based skip reason counts for scalability.
         *     Adding new skip reasons only requires updating the SkipReason enum.
         *
         *     Attributes:
         *         success: Number of successfully processed items.
         *         failed: Number of failed items.
         *         skipped_by_reason: Count of skipped items by reason.
         *
         *     Example:
         *         >>> stats = PhaseStats(
         *         ...     success=8,
         *         ...     failed=1,
         *         ...     skipped_by_reason={SkipReason.FILE_EXISTS: 2}
         *         ... )
         *         >>> stats.skipped  # 2
         *         >>> stats.total    # 11
         *         >>> stats.success_rate  # 72.7...
         */
        PhaseStats: {
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Skipped By Reason */
            skipped_by_reason?: {
                [key: string]: number;
            };
        };
        /**
         * SchedulerStatus
         * @description Scheduler status response.
         */
        SchedulerStatus: {
            /** Running */
            running: boolean;
            /** Enabled */
            enabled: boolean;
            /** Cron Expression */
            cron_expression: string;
            /** Timezone */
            timezone: string;
            /** Next Run At */
            next_run_at: string | null;
            /**
             * Discovery Enabled
             * @default false
             */
            discovery_enabled: boolean;
            /** Discovery Cron */
            discovery_cron?: string | null;
            /** Next Discovery Run At */
            next_discovery_run_at?: string | null;
            subscription_counts: components["schemas"]["SubscriptionCounts"];
        };
        /**
         * SkipReason
         * @description Reason why a track was skipped.
         *
         *     Used in both extraction and download phases:
         *     - Extraction: UNSUPPORTED_VIDEO_TYPE, NO_VIDEO_ID, REGION_UNAVAILABLE
         *     - Download: FILE_EXISTS
         * @enum {string}
         */
        SkipReason: "file_exists" | "unsupported_video_type" | "ugc" | "no_video_id" | "region_unavailable";
        /**
         * SubscriptionCounts
         * @description Subscription count statistics.
         */
        SubscriptionCounts: {
            /** Total */
            total: number;
            /** Enabled */
            enabled: number;
        };
        /**
         * SubscriptionCreate
         * @description Request to create a subscription.
         */
        SubscriptionCreate: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Max Items */
            max_items?: number | null;
        };
        /**
         * SubscriptionListResponse
         * @description List of subscriptions response.
         */
        SubscriptionListResponse: {
            /** Items */
            items: components["schemas"]["SubscriptionResponse"][];
        };
        /**
         * SubscriptionResponse
         * @description Subscription response.
         */
        SubscriptionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["SubscriptionType"];
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Max Items */
            max_items: number | null;
            /**
             * Thumbnail Url
             * Format: uri
             */
            thumbnail_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /**
         * SubscriptionType
         * @description Type of content subscription.
         * @enum {string}
         */
        SubscriptionType: "playlist";
        /**
         * SubscriptionUpdate
         * @description Request to update a subscription.
         */
        SubscriptionUpdate: {
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SuggestionStatus
         * @description Status of a discovery suggestion.
         * @enum {string}
         */
        SuggestionStatus: "pending" | "approved" | "rejected" | "downloaded";
        /**
         * SyncResponse
         * @description Response for sync operations.
         */
        SyncResponse: {
            /** Job Ids */
            job_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * SnapshotEvent
         * @description Initial snapshot of all jobs sent on SSE connection.
         */
        SnapshotEvent: {
            /**
             * Type
             * @default snapshot
             * @constant
             */
            type: "snapshot";
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /**
         * CreatedEvent
         * @description Emitted when a new job is created.
         */
        CreatedEvent: {
            /**
             * Type
             * @default created
             * @constant
             */
            type: "created";
            job: components["schemas"]["Job"];
        };
        /**
         * UpdatedEvent
         * @description Emitted when a job's status or progress changes.
         */
        UpdatedEvent: {
            /**
             * Type
             * @default updated
             * @constant
             */
            type: "updated";
            job: components["schemas"]["Job"];
        };
        /**
         * DeletedEvent
         * @description Emitted when a job is deleted.
         */
        DeletedEvent: {
            /**
             * Type
             * @default deleted
             * @constant
             */
            type: "deleted";
            /** Jobid */
            jobId: string;
        };
        /**
         * ClearedEvent
         * @description Emitted when finished jobs are cleared.
         */
        ClearedEvent: {
            /**
             * Type
             * @default cleared
             * @constant
             */
            type: "cleared";
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_content_info_info_get: {
        parameters: {
            query: {
                /** @description YouTube Music URL (playlist, album, or track) */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Queue is full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_jobs_jobs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearJobsResponse"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelJobResponse"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Job already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Cannot delete running job */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_jobs_jobs_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SnapshotEvent"] | components["schemas"]["CreatedEvent"] | components["schemas"]["UpdatedEvent"] | components["schemas"]["DeletedEvent"] | components["schemas"]["ClearedEvent"];
                };
            };
        };
    };
    get_logs_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
        };
    };
    stream_logs_logs_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LogEntry"];
                };
            };
        };
    };
    cookies_status_cookies_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookiesStatusResponse"];
                };
            };
        };
    };
    upload_cookies_cookies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookiesUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookiesUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cookies_cookies_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CookiesUploadResponse"];
                };
            };
        };
    };
    sync_all_subscriptions_subscriptions_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
        };
    };
    list_subscriptions_subscriptions_get: {
        parameters: {
            query?: {
                enabled?: boolean | null;
                type?: components["schemas"]["SubscriptionType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subscription_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_subscriptions__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subscription_subscriptions__subscription_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_subscription_subscriptions__subscription_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scheduler_status_scheduler_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatus"];
                };
            };
        };
    };
    get_discovery_settings_discovery_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastFmSettingsResponse"] | null;
                };
            };
        };
    };
    update_discovery_settings_discovery_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LastFmSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastFmSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_lastfm_discovery_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LastFmConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastFmSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_lastfm_discovery_disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    run_discovery_scan_discovery_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryScanResponse"];
                };
            };
        };
    };
    list_suggestions_discovery_suggestions_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["SuggestionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySuggestionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discovery_stats_discovery_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryStatsResponse"];
                };
            };
        };
    };
    approve_suggestion_discovery_suggestions__suggestion_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_suggestion_discovery_suggestions__suggestion_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                suggestion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverySuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_approve_suggestions_discovery_suggestions_bulk_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_similar_tracks_playlist_api_discovery_playlists_similar_tracks_post: {
        parameters: {
            query?: {
                top_tracks_limit?: number;
                similar_tracks_per_track?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_discover_playlist_discovery_playlists_discover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverPlaylistResponse"];
                };
            };
        };
    };
}
